### ISSUE TITLE
Can an optional field have an "isIn" array?

### ISSUE THREAD

**Issue by ebaizel** [z0mt3c/node-restify-validation#16]
I've set up an optional query param but it seems to always be required.  I'm thinking it's being rejected because the empty value is not within the isIn array?  Or am I missing something?

Here's the validation:
            animal:
                scope: "query"
                required: false
                isIn: ['cat', 'dog']

**Comment by gchauvet** [comment]
What is your node-restify-validation version ?

**Comment by gchauvet** [comment]
Please provide a snipet or an integration test please (checkout last master branch for integration test)
