### ISSUE TITLE
Please could you update the npm module

### ISSUE THREAD

**Issue by marsanla** [z0mt3c/node-restify-validation#20]
Thanks :)

**Comment by CodersBrothers** [comment]
Perfect! And npm :)

**Comment by CodersBrothers** [comment]
+1, npm publish :P

**Comment by z0mt3c** [comment]
sorry - but it finally happend ;-) thanks for the headsup :+1:

**Comment by CodersBrothers** [comment]
Will be added in NPM as 0.1.2? Now is 0.1.1

**Comment by CodersBrothers** [comment]
Please @z0mt3c reopen this issue. Not it's solved

**Comment by CodersBrothers** [comment]
NPM is on 0.1.1 https://www.npmjs.com/package/node-restify-validation

**Comment by CodersBrothers** [comment]
https://github.com/z0mt3c/node-restify-validation/issues/25
