### ISSUE TITLE
NPM not is updated

### ISSUE THREAD

**Issue by CodersBrothers** [z0mt3c/node-restify-validation#25]
NPM is on 0.1.1 https://www.npmjs.com/package/node-restify-validation

**Comment by z0mt3c** [comment]
Hm have a look for 0.1.3, sorry!

**Comment by gchauvet** [comment]
Hmm project was released as "0.1.3", but they have a major change that's why I upgraded node-restify version to "1.0.3".

**Comment by z0mt3c** [comment]
Sorry for mixing things up...
We now (still) have version 0.1.2 and the new major 1.0.3.
