### ISSUE TITLE
0.1.3 Causes "Unvalid scope" errors for all parameters.

### ISSUE THREAD

**Issue by ebiven** [z0mt3c/node-restify-validation#27]
NPM has a phantom 0.1.3 release, not present here, which doesn't validate but instead will return the following error for every parameter:

```{
"code": "INVALID",
"message": "Unvalid scope. Must be in [resources,queries,content]."
}```

At this point:
https://github.com/z0mt3c/node-restify-validation/blob/master/lib/validation.js#L169

"scope" is the key from the validationModel. ```utils.getExternalScope``` will return undefined for all values except 'resources', 'queries', and 'content'. This causes all validations to fail. This works as expected in 0.1.2.

I would submit a patch but I can't figure out what the intent of the change is since 0.1.2.

**Comment by gchauvet** [comment]
The scope behavior was introduced for 1.x.x version, but was released on NPM repository as "0.1.3" version, but with "1.0.3" sources code. I don't know why.

**Comment by gchauvet** [comment]
https://github.com/z0mt3c/node-restify-validation/issues/25

**Comment by z0mt3c** [comment]
Sorry for mixing things up. 0.1.3 has been unpublished - due to major changes.
