### ISSUE TITLE
Restify validation and restify.bodyParser conflicts

### ISSUE THREAD

**Issue by psychowico** [z0mt3c/node-restify-validation#32]
When I have set `forbidUndefinedVariables: true` and setup bodyParser to map params:
```js
server.use(restify.bodyParser({mapParams: true}));
```
Plugin don't work properly. When I define schema like that:
```js
        validation: {
            resources: {
                id: { isRequired: true, 'swaggerScope': 'path' }
            },
            content: {
                name: { isRequired: false },
                grades: { isRequired: false },
                school: { isRequired: false },
                subjectArea: { isRequired: false },
            }
        },
```
And sending request with content:
```json
{"name": "test"}
```

I got:
```json
{
  "status": "validation failed",
  "errors": {
    "undefined": {
      "scope": "resources",
      "field": "name",
      "code": "UNDEFINED",
      "message": "Variable is not present"
    }
  }
}
```

It is related with bodyParser `mapParams` flag.
I use node-restify-validation@1.0.3.

btw. errors object with `undefined` property (in response) should be only fixed I guess.

**Comment by gchauvet** [comment]
I will look up in the week

**Comment by gchauvet** [comment]
I've created a integration test for your issue (look up commit 8ace9d5621d4520dae25f4e1cd440e77695c4d4b). 
But I can't reproduce what you explain. However, you are (was ?) with node-restify-version 1.0.3; check the current version on master branch please

**Comment by gchauvet** [comment]
Okay I reproduce your error, I work on this issue

**Comment by gchauvet** [comment]
Fixed
