### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by z0mt3c** [z0mt3c/node-restify-validation#35]
Since i'm neither actively using this project nor restify I didn't spent much time to maintaining this project in the past. The good thing is that the api's of its dependencies (e.g. restify) are that stable. For this reason i would love to add a few more maintainers (to take over) this project.

**Comment by gchauvet** [comment]
You are the only one with the right to publication on npmjs

**Comment by z0mt3c** [comment]
Check again ;-)

**Comment by gchauvet** [comment]
okay good ;) thx
