### ISSUE TITLE
validate an array

### ISSUE THREAD

**Issue by robinclark** [z0mt3c/node-restify-validation#39]
Any suggestions on validating an array and its components? For example if you pass a json object in the body and there's an array property

**Comment by gchauvet** [comment]
Can you provide a sample ?
We don't have implemented a JSON schema validator for body contents.
This will be a good feature. I will look up ASAP.

**Comment by bloodfire91** [comment]
I was thinking like if you had an array in the content section you could verify the length and type of its elements. Not sure what would work best with the node-swagger-restify for generating swagger documentation

    server.put({url: '/products/:id/labels/:label', validation: {
      content: {
        coords: { isRequired: true, isArray: { length: 2, itemsType: number }}
      }
    }}, function (req, res, next) {
        res.send(req.params);
    });

**Comment by jarvelov** [comment]
I just invented my own array validator so I figure I might as well share it.

```js
// validators.js
module.exports = {
  isArray: function (param) { // We receive the name of the parameter here
    let value = this.req.params[param]; // Get the value of the param from the request's parameters

    if (Array.isArray(value)) {
      return false; // false indicates that there were no errors (I guess?), backwards logic imo, but hey, it works!
    } else {
      throw new Error('Invalid type: Expected array but received: ' + value.constructor.name);
    }
  }
};
```
I use a custom error handler, hence the throw Error part, but you don't have to. In fact you can even simplify the above check even more with a ternary function: `return !(Array.isArray(this.req.params[param)`

``` js
// server.js

const restify = require('restify');
const restifyValidation = require('node-restify-validation');
const restifyCustomValidators = require('./validators'); // Import our custom validators
const _ = require('lodash'); // Lodash is used to merge the custom validators, but it is optional

...

// Register custom validators
_.extend(restifyValidation.validation._validators, restifyCustomValidators);

// Then use restify-validation as you normally would
server.use(restifyValidation.validationPlugin({ ...
```

``` js
// routes.js

server.post({
  path: '/pages',
  validation: {
    resources: {
      categories: {
        isRequired: true,
        isArray: true
      }
    }
  }
}, function (req, res) { ...
```

And that's it!

Note that this might not be supported and can change in the future. It works with `1.0.5`. But really though, there should exist a supported way to add custom validators, especially since it is so easy!

**Comment by karthikiyengar** [comment]
Thanks for the very useful library. An API like the this would be amazing:

`
{
    isArrayOf: {
        name: { isRequired: true }
    }
}
`

**Comment by gchauvet** [comment]
Don't hesitate to create a pull request :)
I maintain this lib but I currently no longer working with nodeJS

**Comment by karthikiyengar** [comment]
Sure, will try to get to this when I have some free time. Do you have any other observations regarding the proposed API?
