### ISSUE TITLE
Default validation error message is undefined

### ISSUE THREAD

**Issue by alexsk** [z0mt3c/node-restify-validation#41]
File `lib/validation.js` line 140:
```js
var message = validator.msg || validatorCodes.messages[validator.name] || validatorCodes.messages._default;
```
but `validatorCodes.messages._default` is not defined in `lib/validatorCodes.js`

**Comment by gchauvet** [comment]
Can you provide a UT that match this case ?

**Comment by alexsk** [comment]
There is a defined `validatorCodes.codes._default`, but undefined `validatorCodes.messages._default`. And it's not clear for me about `message` field existence. It should be either optional (as we have `if (message)`) than it's better to drop default value from the definition:
```js
var message = validator.msg || validatorCodes.messages[validator.name];
```
or it may be mandatory with some default message text, like `Invalid value` defined as `validatorCodes.messages._default`.
I'd prefer the last case.

Unit test that may cover this case should contain validator without specified message via `msg` field and doesn't have default text in `validatorCodes.js`. It may be either custom validator or something from node-validator library. Let's pick up `isISBN` for example:
```js
it('node-validator error messages', function() {
  var validationReq = { params: {
    ip:    '123',
    isbn:  '123',
    isbn2: '123'
  } };
  var validationModel = { resources: {
    ip:    { isRequired: true, isIP: true },
    isbn:  { isRequired: true, isISBN: true, msg: 'Invalid ISBN' },
    isbn2: { isRequired: true, isISBN: true },
  } };
  var options = { errorsAsArray: true };

  var errors = index.validation.process(validationModel, validationReq, options);
  errors.length.should.equal(3);
  should.exist(errors[0].message);
  should.equal(errors[0].message, 'Invalid IP');   // OK

  should.exist(errors[1].message);
  should.equal(errors[1].message, 'Invalid ISBN'); // OK: msg specified

  should.exist(errors[2].message);                 // FAILS: no default message
  should.equal(errors[2].message, 'Invalid value');
});
```

**Comment by gchauvet** [comment]
Done. I will create a release version ASAP.

**Comment by alexsk** [comment]
Thank you for a quick assistance and a new version.
