### ISSUE TITLE
require library missing?

### ISSUE THREAD

**Issue by m-menon** [z0mt3c/node-restify-validation#43]
hi,

I am pretty new to node, express, restify etc but in the example given, isn't a require statement necessary to include the library?

And also I get the following warning in the console
(node:7580) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

Should something be done about the above warning? And thanks for the validator - it could make my code simpler and easier to read :+1:  Cheers - M.M

**Comment by gchauvet** [comment]
hi,

I'll take a look asap.
What is your node version ?

**Comment by gchauvet** [comment]
We don't call explicitly EventEmitter in our source code, but some development dependencies does.
Re-installing modules in production mode will discard this warning (except if you use development dependencies).

**Comment by m-menon** [comment]
hi,

Sori was away. Just check the node version - it's v.6.1.0. I think the culprit is Node and not node-restify-validation :) Cheers, M.M

**Comment by gchauvet** [comment]
Okay, I close this issue. Thx
