### ISSUE TITLE
Installed package fails nsp check

### ISSUE THREAD

**Issue by cazgp** [z0mt3c/node-restify-validation#48]
validator 3.7.0 has a vulnerability outlined at [nodesecurity](https://nodesecurity.io/advisories/42). The package needs to be updated to >=3.22.1 in order to pass.

**Comment by cazgp** [comment]
I have a PR for this on branch v.1.0.6 of overleaf/node-restify-validation, but since 1.0.5 is two years old and many of the tests don't pass, I'm not sure where to push it.

**Comment by gchauvet** [comment]
I look up on this vulnerability issue ASAP

**Comment by cazgp** [comment]
Thank you :)

**Comment by gchauvet** [comment]
Well I need to spend much effort on this library beacuse 3.22.1 have a new internal behavor....

**Comment by gchauvet** [comment]
fix by #50
