### ISSUE TITLE
Bug in error rendering at HEAD

### ISSUE THREAD

**Issue by JohnieLee** [z0mt3c/node-restify-validation#54]
When I pulled in head, I was getting empty error messages.

It looks like this commit is the culprit: https://github.com/z0mt3c/node-restify-validation/commit/9ad8c8751ec0be533ebe7cfff03109d76b6a549b#commitcomment-19792090

The `createError` method is creating errors that cannot be rendered by `parseErrorMessage`

**Comment by gchauvet** [comment]
Reverted. I sait for fix

**Comment by gchauvet** [comment]
Note: push fix from your previous pull request

**Comment by JohnieLee** [comment]
https://github.com/z0mt3c/node-restify-validation/pull/56  <-- here's the PR

**Comment by gchauvet** [comment]
Done
