### ISSUE TITLE
Push a new NPM update

### ISSUE THREAD

**Issue by JohnieLee** [z0mt3c/node-restify-validation#58]
Could you push the latest HEAD to NPM?

**Comment by gchauvet** [comment]
Yes' this will be à minor release version. I do that on next 24hours

**Comment by JohnieLee** [comment]
Just a friendly ping.

**Comment by gchauvet** [comment]
Tested with npm 3.5.2 and node 4.2.6 : 
- 62 passing
- 20 tests failing

Note : travis report is wrong because @z0mt3c doesn't grant me admin rigths on travis-ci for this repo.
Real result is here :  https://travis-ci.org/gchauvet/node-restify-validation

**Comment by JohnieLee** [comment]
Friendly ping.

**Comment by gchauvet** [comment]
M'y npmjs account is locked atm. Hope support Steam fix m'y case quickly

**Comment by gchauvet** [comment]
Meanwhile, you can point to released tag :
https://github.com/z0mt3c/node-restify-validation/releases/tag/1.1.0

**Comment by JohnieLee** [comment]
Another friendly ping.  Any luck on npmjs support?

**Comment by gchauvet** [comment]
Hi,

Published as 1.1.1 release.
