### ISSUE TITLE
How to define custom validation rule?

### ISSUE THREAD

**Issue by RevathiSk** [z0mt3c/node-restify-validation#9]
Is there any way to define custom validation rule? For instance, I want to check if the password is strong.

passowrd: {isRequired: true,  isPasswordStrong: true }

How to define isPasswordStrong custom rule and its function?

validateIsPasswordStrong(){
   logic to check if password is strong
}

**Comment by MrLeebo** [comment]
I realize this question is old and the original poster is probably long gone, but I'll leave an answer because I found myself asking the same thing:

You can use the `is` validator for custom functions in v0.1.2.

JavaScript
```
password: {
  is: function isStrongPassword() {
    var password = this.req.params.password;
    if (/* password is weak */) {
      throw 'not strong enough';
    }
  },
  msg: 'must be a strong password'
}
```
